# Generated by Django 5.2.2 on 2025-06-09 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professor_responsavel',
            field=models.ForeignKey(limit_choices_to={'is_instructor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor_responsavel',
            field=models.ForeignKey(limit_choices_to={'is_instructor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
