# Generated by Django 5.2.2 on 2025-06-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_curso_professor_responsavel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='data',
            new_name='data_aniversario',
        ),
    ]
