# Generated by Django 5.2.3 on 2025-06-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aluno_edv'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
